# Generated by Django 5.1 on 2024-09-03 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='suntitle',
            new_name='subtitle',
        ),
    ]
